#!/usr/bin/env node

const fs = require("fs")
const commitMessageFile = process.argv[2]

let commitMessage = fs.readFileSync(commitMessageFile, {encoding:'utf8', flag:'r'});
commitMessage = commitMessage.replace('\n', '');
fs.writeFileSync(commitMessageFile, commitMessage + ' [ I got appended with js / node ]');
