#!/usr/bin/env python3

import sys
commit_message_file=sys.argv[1]

# Reading the file then overwriting it. Appending in the same first line in one open does not seem straight-forward.
with open(commit_message_file, "r") as f:
    commit_msg = f.readline()
    commit_msg = commit_msg.replace("\n","")

with open(commit_message_file, "w") as f:
    f.write(commit_msg + " [ I got appended with python]")
